app/articles/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from sqlalchemy import ForeignKey, Integer, String, DateTime

from flask_login import UserMixin

from app.database import Column, Model, SurrogatePK, db, reference_col, relationship
from app.extensions import bcrypt

class Article(SurrogatePK, Model):
    """Article for blog"""
    __tablename__ = 'articles'
    title = Column(String(200))
    body = Column(String())
    created_at = Column(DateTime, nullable=False, default=dt.datetime.utcnow)
    author = Column(Integer, ForeignKey('profiles.id'))
    comments = relationship('Comment', backref='article_link', cascade='delete')

    def __repr__(self):
        return '<Article title={}'.format(self.title)


class Comment(SurrogatePK, Model):
    __tablename__ = 'comments'
    body = Column(String(1000))
    author = Column(Integer, ForeignKey('profiles.id'))
    article = Column(Integer, ForeignKey('articles.id'))
    created_at = Column(DateTime, nullable=False, default=dt.datetime.utcnow)

app/articles/forms.py
# -*- coding: utf-8 -*-
"""Article forms."""
from flask_wtf import Form, FlaskForm
from wtforms import PasswordField, StringField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, Length


class NewArticleForm(FlaskForm):
    title = StringField('Article title', validators=[DataRequired(), Length(min=5, max=200)])
    body = TextAreaField('Article body', validators=[DataRequired(), Length(min=50)])


class NewCommentForm(FlaskForm):
    body = TextAreaField('Comment', validators=[DataRequired()])

app/articles/__init__.py
# -*- coding: utf-8 -*-
"""The articles module, including operations with articles."""
from . import views  # noqa

app/articles/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, session, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .models import Article
from app.user.models import User
from app.articles.models import Comment
from app.articles.forms import NewArticleForm, NewCommentForm
from app.utils import flash_errors
from app.extensions import csrf_protect

blueprint = Blueprint('articles', __name__, url_prefix='/articles', static_folder='../static')


@blueprint.route('/new', methods=['GET', 'POST'])
@login_required
def add_article():
    form = NewArticleForm(request.form, csrf_enabled=True)
    if form.validate_on_submit():
        article = Article.create(title=form.title.data, body=form.body.data, author=current_user.profile.id)
        flash('Article with title "{}" will be added!'.format(article.title), 'success')
        return redirect(url_for('user.members', user_id=current_user.id))
    else:
        flash_errors(form)
    return render_template('articles/new_article.html', form=form, user=current_user)


@blueprint.route('/detail/<article_id>', methods=['GET', 'POST'])
@login_required
def detail_article(article_id):
    article = Article.query.filter(Article.id == article_id).first()
    comments = Comment.query.filter(Comment.article == article_id).order_by(Comment.created_at.desc())
    form = NewCommentForm(csrf_enabled=True)
    return render_template('articles/detail_article.html', form=form, user=current_user, article=article, comments=comments)


@blueprint.route('/edit/<article_id>', methods=['GET', 'POST'])
@login_required
def edit_article(article_id):
    article = Article.query.filter(Article.id == article_id).first()
    if article.author != current_user.profile.id:
        return render_template('404.html')
    form = NewArticleForm(request.form, csrf_enabled=True, title=article.title, body=article.body)
    if form.validate_on_submit():
        article = article.update(title=form.title.data, body=form.body.data)
        flash('Article was be editing.', 'success')
        return redirect(url_for('user.members', user_id=current_user.id))
    else:
        flash_errors(form)
    return render_template('articles/new_article.html', form=form, user=current_user, article=article)


@blueprint.route('/delete/<article_id>')
@login_required
def delete_article(article_id):
    article = Article.query.filter(Article.id == article_id).first()
    if article.author != current_user.profile.id:
        return render_template('404.html')
    article.delete()
    return redirect(url_for('user.members', user_id=current_user.id))


@blueprint.route('/add_comment/<article_id>', methods=['POST'])
@login_required
def add_comment(article_id):
    form = NewCommentForm(request.form, csrf_enabled=True)
    if form.validate_on_submit():
        article = Article.query.filter(Article.id == article_id).first()
        comment = Comment.create(body=form.body.data, author=current_user.profile.id, article=article.id)
        dict = {
            'body': comment.body,
            'author': comment.profile.user.username,
            'created_at': comment.created_at,
            'url_for_delete': url_for('articles.delete_comment', comment_id=comment.id)
        }
        return jsonify(dict)
    else:
        flash_errors(form)
    return redirect(url_for('articles.detail_article', article_id=article_id))


@blueprint.route('/delete_comment/<comment_id>', methods=['POST'])
@login_required
@csrf_protect.exempt
def delete_comment(comment_id):
    comment = Comment.query.filter(Comment.id == comment_id).first()
    if not comment:
        return jsonify({'success': False}), 400

    if comment.author == current_user.profile.id:
        Comment.delete(comment)
        return jsonify({'success': True}), 200

    return jsonify({'success': False}), 403


@blueprint.route('/edit_comment/<comment_id>', methods=['POST'])
@login_required
@csrf_protect.exempt
def edit_comment(comment_id):
    comment = Comment.query.filter(Comment.id == comment_id).first()
    if not comment:
        return jsonify({'success': False}), 400

    form = NewCommentForm(request.form, csrf_enabled=True)

    if comment.author == current_user.profile.id:
        comment.update(body=form.body.data)
        return jsonify({'success': True}), 200

    return jsonify({'success': False}), 403

app/templates/articles/articlesList.html
<div class="row">
    <div class="col-lg-offset-2 col-lg-8">
        <table class="table">
            {% for article in articles.items %}
            <tr>
                <td>
                    <div class="row">
                        <h3 class="col-lg-8 col-md-8 col-sm-8 col-xs-8"><a href="{{ url_for('articles.detail_article', article_id=article.id) }}">
                            {{ article.title }}</a></h3>
                        <small class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-right article__date-publish"><b>Date of publication: {{momentjs(article.created_at).format('HH:mm DD.MM.YYYY')}}</b>
                        </small>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 text-left">
                            Author: <span class="text-muted">{{ article.profile.user.username }}</span> |
                            <a href="{{ url_for('articles.detail_article', article_id=article.id) }}#comments">
                                {% if article.comments|length %}
                                    {{ article.comments|length }} comments
                                {% else %}
                                    Write comment
                                {% endif %}
                            </a>
                        </div>
                    </div>
                    <div class="mce-content-body">{{ article.body|truncate_html(500)|safe }}</div>
                    {% if (current_user and current_user.is_authenticated) %}
                    {% if(current_user.profile.id == article.author) %}
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="{{ url_for('articles.edit_article', article_id=article.id)}}"
                               class="btn btn-primary btn-sm">Edit article</a>
                            <a href="#" data-href="{{ url_for('articles.delete_article', article_id=article.id)}}"
                               class="btn btn-danger btn-sm delete-article" data-toggle="modal" data-target="#deleteArticle">Delete article</a>
                        </div>
                    </div>
                    {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class="text-center">
            <ul class=pagination>
                {% for page in articles.iter_pages(left_edge=2, left_current=2, right_current=2, right_edge=2) %}
                    {% if page %}
                        {% if page != articles.page %}
                            <li><a href="{{ pag_url }}?page={{page}}">{{ page }}</a></li>
                        {% else %}
                            <li class="active"><a href="#">{{ page }}</a></li>
                        {% endif %}
                    {% else %}
                        <li class="disabled"><a href="#">…</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteArticle" role="dialog">
<div class="modal-dialog modal-sm">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Delete article</h4>
    </div>
    <div class="modal-body">
      <p>Are you sure?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-danger btn-sm delete" type="button">Delete article</a>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>
</div>

app/templates/articles/detail_article.html
{% extends "layout.html" %}
{% block css %}
    <link rel="stylesheet" href="https://www.tinymce.com/css/codepen.min.css">
{% endblock %}
{% block content %}
    <div class="detail_article">
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8">
                <div class="row">
                    <div class="col-lg-12">
                        <h2>{{ article.title }}</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="mce-content-body">{{ article.body|safe }}</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <h5>Author: <span class="text-muted">{{ article.profile.user.username }}</span></h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <form id="newComment" method="post" class=""
                              action="{{ url_for('articles.add_comment', article_id=article.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-12">
                                        {{ form.body(placeholder="Comment text", class_="form-control") }}
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-default btn-sm">Add comment</button>
                        </form>
                    </div>
                </div>
                <table id="comments" class="col-lg-12 table">
                    {% for comment in comments %}
                        <tr class="comment">
                            <td>
                                <div class="row">
                                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                                        <h4 class="comment__author">{{ comment.profile.user.username }}</h4>
                                    </div>
                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 text-right comment__date-publish">
                                        <small class="comment__date-publish-text">{{ momentjs(comment.created_at).format('HH:mm DD.MM.YYYY') }}</small>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <p class=" comment__body">
                                            {{ comment.body }}
                                        </p>
                                    </div>
                                </div>
                                {% if(current_user.profile.id == comment.author) %}
                                    <div class="row comment__delete-container">
                                        <div class="col-lg-2">
                                            <a href="{{ url_for('articles.edit_comment', comment_id=comment.id) }}"
                                               class="text-muted small comment__edit-btn">Edit</a>
                                            <a href="{{ url_for('articles.delete_comment', comment_id=comment.id) }}"
                                               class="text-muted small comment__delete-btn">Delete</a>
                                        </div>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/articles/new_article.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <h1 class="col-lg-offset-2 col-lg-8">
        {% if not article %}
            Create article
        {% else %}
            Edit article
        {% endif %}
    </h1>
</div>
<div class="row">
    <div class="col-lg-offset-2 col-lg-8">
        <form id="newArticle" method="post" class="" action="{% if not article %}
                {{ url_for('articles.add_article')}}
            {% else %}
                {{ url_for('articles.edit_article', article_id=article.id)}}
            {% endif %}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                        {{ form.title(placeholder="Title", class_="form-control") }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                        {{ form.body(placeholder="Body", class_="form-control") }}
                    </div>
                </div>
            </div>
            {% if article %}
            <button type="submit" class="btn btn-default">Save Article</button>
            {% else %}
            <button type="submit" class="btn btn-default">Create Article</button>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='libs/tinymce/tinymce.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/tinymceInit.js') }}"></script>
{% endblock %}